// Emits 03-staging-import.sql against the `scrapyards_staging` schema.

import fs from "node:fs";
import { sqlString, sqlJsonb, sqlTextArray, sqlNumeric } from "./util.js";
import type { CityRow, YardRow } from "./transform.js";
import { STATES } from "./states.js";
import { METALS } from "./metals.js";
import { buildRedirects, readGscPaths, type Redirect } from "./build-redirects.js";
import path from "node:path";
import { fileURLToPath } from "node:url";

const SCHEMA = "scrapyards_staging";

const HEADER = `-- migration/output/03-staging-import.sql — generated by @workspace/migration ETL
-- Target schema: ${SCHEMA} (NEVER public, NEVER production)
-- Idempotent: every INSERT uses ON CONFLICT DO UPDATE so reruns converge.

SET search_path TO ${SCHEMA};
`;

const DDL = `CREATE SCHEMA IF NOT EXISTS ${SCHEMA};
SET search_path TO ${SCHEMA};

CREATE TABLE IF NOT EXISTS states (
  code char(2) PRIMARY KEY,
  slug varchar(40) NOT NULL UNIQUE,
  name varchar(60) NOT NULL,
  fips char(2) NOT NULL,
  lat numeric(9,6),
  lng numeric(9,6),
  intro_md text,
  laws_md text
);

CREATE TABLE IF NOT EXISTS cities (
  id serial PRIMARY KEY,
  state_code char(2) NOT NULL REFERENCES states(code),
  slug varchar(80) NOT NULL,
  name varchar(100) NOT NULL,
  population integer,
  lat numeric(9,6),
  lng numeric(9,6),
  CONSTRAINT cities_state_slug_unique UNIQUE (state_code, slug)
);
CREATE INDEX IF NOT EXISTS cities_state_idx ON cities (state_code);

CREATE TABLE IF NOT EXISTS metal_categories (
  slug varchar(40) PRIMARY KEY,
  name varchar(80) NOT NULL,
  description_md text,
  display_order integer DEFAULT 100
);

CREATE TABLE IF NOT EXISTS metals (
  slug varchar(60) PRIMARY KEY,
  name varchar(120) NOT NULL,
  category varchar(40) NOT NULL,
  unit varchar(10) NOT NULL,
  description_md text,
  prep_tips_md text,
  spot_factor numeric(4,3),
  spot_metal varchar(20),
  display_order integer DEFAULT 100
);

CREATE TABLE IF NOT EXISTS yards (
  id serial PRIMARY KEY,
  slug varchar(120) NOT NULL,
  name varchar(200) NOT NULL,
  state_code char(2) NOT NULL REFERENCES states(code),
  city_id integer NOT NULL REFERENCES cities(id),
  address varchar(255),
  zip varchar(10),
  lat numeric(9,6),
  lng numeric(9,6),
  phone varchar(20),
  website varchar(255),
  email varchar(120),
  hours jsonb,
  accepted text[],
  services text[],
  description text,
  photo_urls text[],
  rating_avg numeric(2,1),
  rating_count integer DEFAULT 0,
  is_verified boolean DEFAULT false,
  is_premium boolean DEFAULT false,
  status varchar(20) DEFAULT 'active',
  legacy_url varchar(500),
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  CONSTRAINT yards_state_city_slug_unique UNIQUE (state_code, city_id, slug)
);
CREATE INDEX IF NOT EXISTS yards_state_city_idx ON yards (state_code, city_id);
CREATE INDEX IF NOT EXISTS yards_legacy_url_idx ON yards (legacy_url);

CREATE TABLE IF NOT EXISTS legacy_redirects (
  source_path varchar(500) PRIMARY KEY,
  target_path varchar(500) NOT NULL,
  status_code smallint DEFAULT 301
);
`;

// Seeded `metal_categories` (mirrors scripts/src/seed-scrapyards.ts).
const METAL_CATEGORIES: Array<{ slug: string; name: string; displayOrder: number }> = [
  { slug: "copper", name: "Copper", displayOrder: 10 },
  { slug: "aluminum", name: "Aluminum", displayOrder: 20 },
  { slug: "steel", name: "Steel & Iron", displayOrder: 30 },
  { slug: "brass", name: "Brass", displayOrder: 40 },
  { slug: "lead", name: "Lead", displayOrder: 50 },
  { slug: "zinc", name: "Zinc", displayOrder: 60 },
  { slug: "electronics", name: "Electronics (E-Scrap)", displayOrder: 70 },
  { slug: "precious-metals", name: "Precious Metals", displayOrder: 80 },
  { slug: "auto-parts", name: "Auto Parts", displayOrder: 90 },
];

function batchInserts<T>(items: T[], rowSql: (t: T) => string, header: string, batchSize = 500): string {
  const out: string[] = [];
  for (let i = 0; i < items.length; i += batchSize) {
    const slice = items.slice(i, i + batchSize);
    out.push(header);
    out.push(slice.map(rowSql).join(",\n"));
    out.push("ON CONFLICT DO NOTHING;\n");
  }
  return out.join("\n");
}

function statesSql(): string {
  const rows = STATES.map(
    (s) =>
      `(${sqlString(s.code)}, ${sqlString(s.slug)}, ${sqlString(s.name)}, ${sqlString(s.fips)}, ${sqlNumeric(s.lat)}, ${sqlNumeric(s.lng)})`
  );
  return `INSERT INTO states (code, slug, name, fips, lat, lng) VALUES
${rows.join(",\n")}
ON CONFLICT (code) DO UPDATE SET
  slug = EXCLUDED.slug,
  name = EXCLUDED.name,
  fips = EXCLUDED.fips,
  lat = EXCLUDED.lat,
  lng = EXCLUDED.lng;
`;
}

function metalsSql(): string {
  const rows = METALS.map(
    (m) =>
      `(${sqlString(m.slug)}, ${sqlString(m.name)}, ${sqlString(m.category)}, ${sqlString(m.unit)}, ${sqlNumeric(m.spotFactor)}, ${sqlString(m.spotMetal)}, ${m.displayOrder})`
  );
  return `INSERT INTO metals (slug, name, category, unit, spot_factor, spot_metal, display_order) VALUES
${rows.join(",\n")}
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  unit = EXCLUDED.unit,
  spot_factor = EXCLUDED.spot_factor,
  spot_metal = EXCLUDED.spot_metal,
  display_order = EXCLUDED.display_order;
`;
}

function metalCategoriesSql(): string {
  const rows = METAL_CATEGORIES.map(
    (c) =>
      `(${sqlString(c.slug)}, ${sqlString(c.name)}, NULL, ${c.displayOrder})`
  );
  return `INSERT INTO metal_categories (slug, name, description_md, display_order) VALUES
${rows.join(",\n")}
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  display_order = EXCLUDED.display_order;
`;
}

function citiesSql(cities: CityRow[]): string {
  if (cities.length === 0) return "-- (no cities)\n";
  const rows = cities.map(
    (c) =>
      `(${c._id}, ${sqlString(c.state_code)}, ${sqlString(c.slug)}, ${sqlString(c.name.slice(0, 100))}, ${sqlNumeric(c.lat)}, ${sqlNumeric(c.lng)})`
  );
  // We force IDs (so yards can reference them deterministically), then resync
  // the serial sequence below.
  const out: string[] = [];
  out.push(`INSERT INTO cities (id, state_code, slug, name, lat, lng) VALUES`);
  // Batch into chunks for readability.
  const batchSize = 500;
  for (let i = 0; i < rows.length; i += batchSize) {
    const slice = rows.slice(i, i + batchSize);
    if (i > 0) out.push(`INSERT INTO cities (id, state_code, slug, name, lat, lng) VALUES`);
    out.push(slice.join(",\n"));
    out.push(`ON CONFLICT (state_code, slug) DO UPDATE SET
  name = EXCLUDED.name,
  lat = EXCLUDED.lat,
  lng = EXCLUDED.lng;
`);
  }
  out.push(`SELECT setval(pg_get_serial_sequence('${SCHEMA}.cities', 'id'), (SELECT COALESCE(MAX(id), 1) FROM cities));`);
  return out.join("\n");
}

function yardRowSql(y: YardRow): string {
  return (
    `(${sqlString(y.slug)}, ${sqlString(y.name)}, ${sqlString(y.state_code)}, ${y.city_id}, ` +
    `${sqlString(y.address)}, ${sqlString(y.zip)}, ${sqlNumeric(y.lat)}, ${sqlNumeric(y.lng)}, ` +
    `${sqlString(y.phone)}, ${sqlString(y.website)}, ${sqlString(y.email)}, ${sqlJsonb(y.hours)}, ` +
    `${sqlTextArray(y.accepted)}, ${sqlTextArray(y.services)}, ${sqlString(y.status)}, ${sqlString(y.legacy_url)})`
  );
}

function yardsSql(yards: YardRow[]): string {
  if (yards.length === 0) return "-- (no yards)\n";
  const header = `INSERT INTO yards (slug, name, state_code, city_id, address, zip, lat, lng, phone, website, email, hours, accepted, services, status, legacy_url) VALUES`;
  const out: string[] = [];
  const batchSize = 250;
  for (let i = 0; i < yards.length; i += batchSize) {
    const slice = yards.slice(i, i + batchSize);
    out.push(header);
    out.push(slice.map(yardRowSql).join(",\n"));
    out.push(`ON CONFLICT (state_code, city_id, slug) DO UPDATE SET
  name = EXCLUDED.name,
  address = EXCLUDED.address,
  zip = EXCLUDED.zip,
  lat = EXCLUDED.lat,
  lng = EXCLUDED.lng,
  phone = EXCLUDED.phone,
  website = EXCLUDED.website,
  email = EXCLUDED.email,
  hours = EXCLUDED.hours,
  accepted = EXCLUDED.accepted,
  services = EXCLUDED.services,
  status = EXCLUDED.status,
  legacy_url = EXCLUDED.legacy_url,
  updated_at = now();
`);
  }
  return out.join("\n");
}

function legacyRedirectsSql(items: Redirect[]): string {
  if (items.length === 0) return "-- (no legacy redirects)\n";
  const header = `INSERT INTO legacy_redirects (source_path, target_path, status_code) VALUES`;
  const out: string[] = [];
  const batchSize = 500;
  for (let i = 0; i < items.length; i += batchSize) {
    const slice = items.slice(i, i + batchSize);
    out.push(header);
    out.push(slice.map((r) => `(${sqlString(r.source)}, ${sqlString(r.target)}, ${r.status})`).join(",\n"));
    out.push(`ON CONFLICT (source_path) DO UPDATE SET
  target_path = EXCLUDED.target_path,
  status_code = EXCLUDED.status_code;
`);
  }
  return out.join("\n");
}

export function writeStagingSql(
  outFile: string,
  cities: CityRow[],
  yards: YardRow[]
): void {
  const HERE = path.dirname(fileURLToPath(import.meta.url));
  const REPO = path.resolve(HERE, "../../..");
  const gscPaths = readGscPaths(path.join(REPO, "migration/input/gsc-pages.csv"));
  const { all: redirects } = buildRedirects({ cities, yards, gscPaths });

  const parts: string[] = [];
  parts.push(HEADER);
  parts.push("-- 1. DDL\n");
  parts.push(DDL);
  parts.push("-- 2. Truncate yards/cities/legacy_redirects to keep the load deterministic.");
  parts.push(`-- (states + metal_categories are upserted; we never blow them away.)`);
  parts.push(`TRUNCATE TABLE legacy_redirects;`);
  parts.push(`TRUNCATE TABLE yards RESTART IDENTITY CASCADE;`);
  parts.push(`TRUNCATE TABLE cities RESTART IDENTITY CASCADE;\n`);
  parts.push("-- 3. states (canonical seed)\n");
  parts.push(statesSql());
  parts.push("\n-- 4. metal_categories (canonical seed)\n");
  parts.push(metalCategoriesSql());
  parts.push(`\n-- 4b. metals (canonical 22-row catalog; D2 Option A — no WP metal posts imported)\n`);
  parts.push(metalsSql());
  parts.push(`\n-- 5. cities (${cities.length} rows)\n`);
  parts.push(citiesSql(cities));
  parts.push(`\n-- 6. yards (${yards.length} rows)\n`);
  parts.push(yardsSql(yards));
  parts.push(`\n-- 7. legacy_redirects (${redirects.length} rows: synthetic parents + canonical winner legacy URLs + dedupe-loser URLs + GSC sweep)\n`);
  parts.push(legacyRedirectsSql(redirects));
  fs.writeFileSync(outFile, parts.join("\n"));
}

export function writeSkippedCsv(outFile: string, skipped: Array<{ post_id: string; raw_slug: string; reason: string; details?: string }>): void {
  const lines = ["post_id,raw_slug,reason,details"];
  for (const s of skipped) {
    const det = (s.details ?? "").replace(/"/g, '""');
    lines.push(`${s.post_id},"${s.raw_slug.replace(/"/g, '""')}",${s.reason},"${det}"`);
  }
  fs.writeFileSync(outFile, lines.join("\n") + "\n");
}
